export const necklaces = [
  {
    id: "NL001",
    name: "Elegant Pearl Necklace",
    image: "/images/necklace01.jpg",
    status: "available",
    price: 120.99,
    description: "A classic pearl necklace that adds elegance to any outfit.",
  },
  {
    id: "NL002",
    name: "Gold Chain Necklace",
    image: "/images/necklace02.jpg",
    status: "out of stock",
    price: 150.5,
    description: "A premium 18K gold chain, perfect for everyday wear.",
  },
  {
    id: "NL003",
    name: "Silver Heart Pendant",
    image: "/images/necklace03.jpg",
    status: "available",
    price: 75.0,
    description: "A beautiful silver necklace with a heart-shaped pendant.",
  },
  {
    id: "NL004",
    name: "Crystal Choker Necklace",
    image: "/images/necklace04.jpg",
    status: "available",
    price: 89.99,
    description: "A stunning crystal choker that shines in the light.",
  },
  {
    id: "NL005",
    name: "Diamond Infinity Necklace",
    image: "/images/necklace05.jpg",
    status: "available",
    price: 250.0,
    description: "An elegant infinity-shaped pendant with sparkling diamonds.",
  },
  {
    id: "NL006",
    name: "Rose Gold Layered Necklace",
    image: "/images/necklace06.jpg",
    status: "available",
    price: 110.75,
    description: "A trendy layered necklace in rose gold for a stylish look.",
  },
  {
    id: "NL007",
    name: "Vintage Locket Necklace",
    image: "/images/necklace07.jpg",
    status: "out of stock",
    price: 130.0,
    description:
      "A vintage-style locket necklace with a hidden photo compartment.",
  },
  {
    id: "NL008",
    name: "Minimalist Bar Necklace",
    image: "/images/necklace08.jpg",
    status: "available",
    price: 60.99,
    description: "A sleek and simple bar necklace for a modern touch.",
  },
  {
    id: "NL009",
    name: "Bohemian Beaded Necklace",
    image: "/images/necklace09.jpg",
    status: "available",
    price: 45.5,
    description: "A colorful bohemian necklace with intricate beadwork.",
  },
  {
    id: "NL010",
    name: "Moon & Star Pendant Necklace",
    image: "/images/necklace10.jpg",
    status: "available",
    price: 85.0,
    description:
      "A celestial-inspired necklace featuring a moon and star pendant.",
  },
  {
    id: "NL011",
    name: "Golden Elegance",
    image: "/images/necklace11.jpg",
    status: "available",
    price: 120.99,
    description: "A stunning gold-plated necklace with intricate detailing.",
  },
  {
    id: "NL012",
    name: "Silver Serenity",
    image: "/images/necklace12.jpg",
    status: "out of stock",
    price: 85.5,
    description: "Elegant silver necklace with a minimalist charm.",
  },
  {
    id: "NL013",
    name: "Pearl Grace",
    image: "/images/necklace13.jpg",
    status: "available",
    price: 150.0,
    description: "Classic pearl necklace for timeless beauty.",
  },
  {
    id: "NL014",
    name: "Ruby Radiance",
    image: "/images/necklace14.jpg",
    status: "available",
    price: 230.75,
    description: "A luxurious ruby-embedded necklace for a royal look.",
  },
  {
    id: "NL015",
    name: "Emerald Essence",
    image: "/images/necklace15.jpg",
    status: "available",
    price: 199.99,
    description: "An emerald gemstone necklace exuding sophistication.",
  },
  {
    id: "NL016",
    name: "Sapphire Sparkle",
    image: "/images/necklace16.jpg",
    status: "available",
    price: 215.5,
    description: "A dazzling sapphire-adorned necklace with a radiant glow.",
  },
  {
    id: "NL017",
    name: "Diamond Delight",
    image: "/images/necklace17.jpg",
    status: "out of stock",
    price: 350.0,
    description: "Exquisite diamond necklace for an elegant touch.",
  },
  {
    id: "NL018",
    name: "Rose Gold Charm",
    image: "/images/necklace18.jpg",
    status: "available",
    price: 99.99,
    description: "A delicate rose gold necklace with a heart pendant.",
  },
  {
    id: "NL019",
    name: "Crystal Bloom",
    image: "/images/necklace19.jpg",
    status: "available",
    price: 75.0,
    description: "A crystal-embedded floral necklace for a chic style.",
  },
  {
    id: "NL020",
    name: "Amethyst Aura",
    image: "/images/necklace20.jpg",
    status: "available",
    price: 180.25,
    description: "An enchanting amethyst stone necklace for a mystical appeal.",
  },
  {
    id: "NL021",
    name: "Platinum Shine Necklace",
    image: "/images/necklace21.jpg",
    status: "available",
    price: 299.99,
    description: "A premium platinum necklace with a sleek design.",
  },
  {
    id: "NL022",
    name: "Black Onyx Pendant",
    image: "/images/necklace22.jpg",
    status: "available",
    price: 99.5,
    description: "A mysterious black onyx pendant on a silver chain.",
  },
  {
    id: "NL023",
    name: "Opal Dream Necklace",
    image: "/images/necklace23.jpg",
    status: "out of stock",
    price: 189.75,
    description: "A mesmerizing opal gemstone necklace for a dreamy vibe.",
  },
  {
    id: "NL024",
    name: "Citrine Sunlight Necklace",
    image: "/images/necklace24.jpg",
    status: "available",
    price: 165.0,
    description: "A bright citrine stone necklace radiating warmth.",
  },
  {
    id: "NL025",
    name: "Turquoise Boho Necklace",
    image: "/images/necklace25.jpg",
    status: "available",
    price: 78.5,
    description: "A turquoise beaded necklace with bohemian charm.",
  },
  {
    id: "NL026",
    name: "Garnet Passion Necklace",
    image: "/images/necklace26.jpg",
    status: "available",
    price: 140.0,
    description: "A deep red garnet necklace symbolizing passion and energy.",
  },
  {
    id: "NL027",
    name: "Topaz Tranquility Necklace",
    image: "/images/necklace27.jpg",
    status: "available",
    price: 190.0,
    description: "A light blue topaz necklace promoting peace and calmness.",
  },
  {
    id: "NL028",
    name: "Amber Glow Necklace",
    image: "/images/necklace28.jpg",
    status: "available",
    price: 135.5,
    description: "A warm amber stone necklace exuding natural beauty.",
  },
  {
    id: "NL029",
    name: "Aquamarine Ocean Necklace",
    image: "/images/necklace29.jpg",
    status: "out of stock",
    price: 220.99,
    description: "An aquamarine gemstone necklace inspired by ocean waves.",
  },
  {
    id: "NL030",
    name: "Lapis Lazuli Mystique",
    image: "/images/necklace30.jpg",
    status: "available",
    price: 175.0,
    description: "A lapis lazuli necklace bringing wisdom and strength.",
  },
];
